<a href="https://colab.research.google.com/github/donjadao/lis4693_don_jacky_final_project/blob/main/Amazon%20Data%20Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Took this dataset and filtering it to only have ramen reviews: https://www.kaggle.com/datasets/snap/amazon-fine-food-reviews?resource=download

In [5]:
import pandas as pd

In [1]:
!ls

Reviews.csv  sample_data

In [6]:
df = pd.read_csv("Reviews.csv")

In [7]:
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

Filtering the csv to only contain reviews about ramen

In [9]:
ramen_df = df[
    df["Text"].str.contains(
        "ramen|instant noodle|cup noodle",
        case=False,
        na=False
    )
]

ramen_df = ramen_df[ramen_df["Text"].str.len() >= 150]

len(ramen_df)

1241

In [10]:
ramen_df["Text"].iloc[0]

"I've been a fan of Hot & Spicy Maruchan Ramen for a long time. If you enjoy spice, and love ramen, you'll love this product. Too bad it's way too expensive here on Amazon. It's only $3.36 per 12 at my Walmart."

Getting only certain columns, deleting columns such as user id

In [19]:
ramen_df = ramen_df[
    ["ProductId", "Score", "Summary", "Text", "Time",
     "HelpfulnessNumerator", "HelpfulnessDenominator"]
]

In [20]:
ramen_df.head(10)

,ProductId,Score,Summary,Text,Time,HelpfulnessNumerator,HelpfulnessDenominator
0,B003OB0IB8,4,Tastes great. Love Hot & Spicy. Bad price here.,I've been a fan of Hot & Spicy Maruchan Ramen ...,1325808000,4,4
1,B003OB0IB8,5,My favorite ramen,I've been eating Ramen noodles since I was a l...,1314489600,4,4
2,B003OB0IB8,3,It burns!,"I LOVE spicy ramen, but for whatever reasons t...",1329436800,3,3
3,B003OB0IB8,5,Amazing to the last bite.,Always being a fan of ramen as a quick and eas...,1330473600,1,1
4,B003OB0IB8,4,"Tastes great, but is cheaper locally.",I love this flavor of ramen! I don't eat other...,1333756800,0,0
5,B0009XLVGA,5,My cat loves it!,I started my cat on Felidae Platinum about 3 w...,1267920000,2,2
6,B000G6RYNE,5,My favorite Kettle Chip,"These are my favorite, but they aren't for eve...",1327968000,1,1
7,B0017WFN4S,5,Like tiny light flavored peanut halves....,"Excellent in cereal, or on top icecream sundae...",1332288000,0,0
8,B003OB2EP6,5,The best around,I'm not so sure why the other guy didn't like ...,1316995200,3,3
9,B003OB2EP6,3,"Okay price, fast easy meals","This is ramen, a cheap, easy, and fast noodle ...",1334275200,1,1

In [13]:
ramen_df.to_csv("ramen_reviews_long.csv", index=False)

In [14]:
!ls

ramen_reviews_long.csv	Reviews.csv  sample_data